### ISSUE TITLE
How do you make hurt notes?

### ISSUE THREAD

**Issue by MayonnaiseGit** [cabalex/fnf-song-converter#10]
I'm trying to port one of the Vs. /V/ songs, Infini***r (of course I changed the name in the project) but I can't figure out how to make the pain notes. I have the sprites and all but I don't know how to program them in

Edit: Another problem is that the converter also turns hurt notes into notes you're supposed to hit instead of completely ignoring them, making the song even harder to beat.

**Comment by cabalex** [comment]
[See the wiki](https://github.com/cabalex/fnf-song-converter/wiki#what-about-hurt-notes). My engine project does not support this natively, so you'll have to build it yourself or get it from a project that has already handled it. I can't code your mods for you!

---
I should note that this is not the place to ask questions about how to do stuff- this is only for issues relating solely to the converter. For those, ask on [my profile](https://scratch.mit.edu/users/cabalex) and I'll get to it when I can. Depending how hurt notes are handled, they should work if you built in support for it. If it relies on an external file or extra data that isn't native to the game, I won't build it in for reasons I've already outlined.

**Comment by cabalex** [comment]
Edit: I just realized this is an issue with the converter- modified notes are falsely detected! I've modified this so that the "limit to default range (0-7)" and "ignore unexpected notes" settings ignore these notes, and that the other two settings show extra data for when these notes appear. Thanks for reporting it, and I apologize if I acted a bit prematurely.
